-- EUNOIA CLOUD DATABASE SCHEMA
-- Instructions: Copy this entire file and paste it into the Supabase SQL Editor, then click "Run".

-- 1. Users Table
CREATE TABLE users (
  id UUID PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  pin TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  last_seen BIGINT,
  session_count INTEGER DEFAULT 0,
  profile_notes TEXT DEFAULT ''
);

-- 2. Sessions Table
CREATE TABLE sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  started_at BIGINT NOT NULL,
  ended_at BIGINT,
  phase TEXT DEFAULT 'check_in',
  turn_count INTEGER DEFAULT 0,
  summary TEXT DEFAULT '',
  distortions_worked TEXT DEFAULT '',
  symptoms_addressed TEXT DEFAULT ''
);

-- 3. Messages Table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  timestamp BIGINT NOT NULL,
  arousal_state TEXT DEFAULT 'window_of_tolerance',
  distortions TEXT DEFAULT '',
  symptoms TEXT DEFAULT ''
);

-- 4. User Patterns Table
CREATE TABLE user_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pattern_type TEXT NOT NULL,
  pattern_value TEXT NOT NULL,
  first_seen BIGINT NOT NULL,
  last_seen BIGINT NOT NULL,
  frequency INTEGER DEFAULT 1
);

-- Disable Row Level Security (RLS) since we handle auth entirely in our Node server
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_patterns DISABLE ROW LEVEL SECURITY;
